// ============================================
// QUICKARDS — Starter gallery templates
// ============================================
//
// Phase 9 ships with three public starters so the marketing gallery has
// indexable pages immediately and users can fork without separate manual seeding.

import { emptyDocument, newId, type CardDocument } from "@/lib/design/schema";

export type StarterGalleryTemplate = {
  slug: string;
  name: string;
  category: string;
  document: CardDocument;
};

const makeStudentId = (): CardDocument => {
  const base = emptyDocument();
  return {
    ...base,
    sides: [
      {
        ...base.sides[0],
        background: { kind: "color", color: "#FFFFFF" },
        children: [
          {
            id: newId(),
            name: "Top band",
            type: "shape",
            locked: false,
            hidden: false,
            shadow: null,
            transform: {
              x: 0,
              y: 0,
              width: base.canvas.width,
              height: 165,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
            shape: { kind: "rect", cornerRadius: 0 },
            fill: "#1F2937",
            stroke: null,
          },
          {
            id: newId(),
            name: "Name",
            type: "text",
            locked: false,
            hidden: false,
            shadow: null,
            content: { source: "template", pattern: "{{name}}", fallback: "Student Name" },
            stroke: null,
            transform: {
              x: 280,
              y: 248,
              width: 620,
              height: 72,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
            typography: {
              fontFamily: "Inter",
              fontWeight: 700,
              fontStyle: "normal",
              fontSize: 52,
              lineHeight: 1.2,
              letterSpacing: 0,
              textAlign: "left",
              verticalAlign: "top",
              textTransform: "none",
              underline: false,
              color: "#111827",
              autoFit: "shrink",
              minFontSize: 18,
              maxLines: 1,
            },
          },
          {
            id: newId(),
            name: "Department",
            type: "text",
            locked: false,
            hidden: false,
            shadow: null,
            content: { source: "template", pattern: "{{department}}", fallback: "Computer Science" },
            stroke: null,
            transform: {
              x: 280,
              y: 334,
              width: 500,
              height: 44,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
            typography: {
              fontFamily: "Inter",
              fontWeight: 500,
              fontStyle: "normal",
              fontSize: 30,
              lineHeight: 1.2,
              letterSpacing: 0,
              textAlign: "left",
              verticalAlign: "top",
              textTransform: "none",
              underline: false,
              color: "#4B5563",
              autoFit: "shrink",
              minFontSize: 12,
              maxLines: 1,
            },
          },
          {
            id: newId(),
            name: "ID code",
            type: "code",
            locked: false,
            hidden: false,
            shadow: null,
            symbology: "qr",
            value: { source: "template", pattern: "{{card_id}}", fallback: "STU001" },
            foreground: "#111827",
            background: null,
            errorCorrection: "M",
            quietZone: 0,
            transform: {
              x: 830,
              y: 420,
              width: 136,
              height: 136,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
          },
        ],
      },
    ],
  };
};

const makeEventPass = (): CardDocument => {
  const base = emptyDocument();
  return {
    ...base,
    sides: [
      {
        ...base.sides[0],
        background: { kind: "color", color: "#0F172A" },
        children: [
          {
            id: newId(),
            name: "Accent strip",
            type: "shape",
            locked: false,
            hidden: false,
            shadow: null,
            transform: {
              x: 0,
              y: 0,
              width: 86,
              height: base.canvas.height,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
            shape: { kind: "rect", cornerRadius: 0 },
            fill: "#DC2626",
            stroke: null,
          },
          {
            id: newId(),
            name: "Event title",
            type: "text",
            locked: false,
            hidden: false,
            shadow: null,
            content: { source: "template", pattern: "{{event_name}}", fallback: "Summit 2026" },
            stroke: null,
            transform: {
              x: 130,
              y: 112,
              width: 760,
              height: 78,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
            typography: {
              fontFamily: "Inter",
              fontWeight: 700,
              fontStyle: "normal",
              fontSize: 56,
              lineHeight: 1.2,
              letterSpacing: 0,
              textAlign: "left",
              verticalAlign: "top",
              textTransform: "none",
              underline: false,
              color: "#FFFFFF",
              autoFit: "shrink",
              minFontSize: 18,
              maxLines: 1,
            },
          },
          {
            id: newId(),
            name: "Attendee",
            type: "text",
            locked: false,
            hidden: false,
            shadow: null,
            content: { source: "template", pattern: "{{name}}", fallback: "Attendee Name" },
            stroke: null,
            transform: {
              x: 130,
              y: 236,
              width: 700,
              height: 60,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
            typography: {
              fontFamily: "Inter",
              fontWeight: 600,
              fontStyle: "normal",
              fontSize: 44,
              lineHeight: 1.2,
              letterSpacing: 0,
              textAlign: "left",
              verticalAlign: "top",
              textTransform: "none",
              underline: false,
              color: "#E5E7EB",
              autoFit: "shrink",
              minFontSize: 14,
              maxLines: 1,
            },
          },
          {
            id: newId(),
            name: "Pass type",
            type: "text",
            locked: false,
            hidden: false,
            shadow: null,
            content: { source: "template", pattern: "{{pass_type}}", fallback: "All Access" },
            stroke: null,
            transform: {
              x: 130,
              y: 314,
              width: 360,
              height: 42,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
            typography: {
              fontFamily: "Inter",
              fontWeight: 500,
              fontStyle: "normal",
              fontSize: 28,
              lineHeight: 1.2,
              letterSpacing: 0,
              textAlign: "left",
              verticalAlign: "top",
              textTransform: "uppercase",
              underline: false,
              color: "#DC2626",
              autoFit: "shrink",
              minFontSize: 12,
              maxLines: 1,
            },
          },
        ],
      },
    ],
  };
};

const makeVisitorBadge = (): CardDocument => {
  const base = emptyDocument();
  return {
    ...base,
    sides: [
      {
        ...base.sides[0],
        background: { kind: "color", color: "#F8FAFC" },
        children: [
          {
            id: newId(),
            name: "Header",
            type: "shape",
            locked: false,
            hidden: false,
            shadow: null,
            transform: {
              x: 0,
              y: 0,
              width: base.canvas.width,
              height: 134,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
            shape: { kind: "rect", cornerRadius: 0 },
            fill: "#0EA5E9",
            stroke: null,
          },
          {
            id: newId(),
            name: "Visitor name",
            type: "text",
            locked: false,
            hidden: false,
            shadow: null,
            content: { source: "template", pattern: "{{name}}", fallback: "Visitor Name" },
            stroke: null,
            transform: {
              x: 52,
              y: 212,
              width: 620,
              height: 66,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
            typography: {
              fontFamily: "Inter",
              fontWeight: 700,
              fontStyle: "normal",
              fontSize: 48,
              lineHeight: 1.2,
              letterSpacing: 0,
              textAlign: "left",
              verticalAlign: "top",
              textTransform: "none",
              underline: false,
              color: "#0F172A",
              autoFit: "shrink",
              minFontSize: 16,
              maxLines: 1,
            },
          },
          {
            id: newId(),
            name: "Company",
            type: "text",
            locked: false,
            hidden: false,
            shadow: null,
            content: { source: "template", pattern: "{{company}}", fallback: "Guest Company" },
            stroke: null,
            transform: {
              x: 52,
              y: 292,
              width: 620,
              height: 40,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
            typography: {
              fontFamily: "Inter",
              fontWeight: 500,
              fontStyle: "normal",
              fontSize: 27,
              lineHeight: 1.2,
              letterSpacing: 0,
              textAlign: "left",
              verticalAlign: "top",
              textTransform: "none",
              underline: false,
              color: "#334155",
              autoFit: "shrink",
              minFontSize: 12,
              maxLines: 1,
            },
          },
          {
            id: newId(),
            name: "Badge code",
            type: "code",
            locked: false,
            hidden: false,
            shadow: null,
            symbology: "qr",
            value: { source: "template", pattern: "{{card_id}}", fallback: "VIS001" },
            foreground: "#0F172A",
            background: null,
            errorCorrection: "M",
            quietZone: 0,
            transform: {
              x: 810,
              y: 398,
              width: 162,
              height: 162,
              rotation: 0,
              opacity: 1,
              flipX: false,
              flipY: false,
            },
          },
        ],
      },
    ],
  };
};

export const STARTER_GALLERY_TEMPLATES: StarterGalleryTemplate[] = [
  {
    slug: "student-id",
    name: "Student ID",
    category: "Student ID",
    document: makeStudentId(),
  },
  {
    slug: "event-pass",
    name: "Event Pass",
    category: "Event Pass",
    document: makeEventPass(),
  },
  {
    slug: "visitor-badge",
    name: "Visitor Badge",
    category: "Visitor Badge",
    document: makeVisitorBadge(),
  },
];

