// ============================================
// QUICKARDS — SvgIR → SVG string (server emitter)
// ============================================
//
// Consumed by resvg. Note what is NOT here: no geometry, no font handling, no
// binding resolution, no conditional logic about node types. It walks a tree
// and writes tags. That is the whole job, and it is why this emitter cannot
// disagree with the editor about where anything goes.

import type { SvgIR } from "./ir";

/** Elements that must not be self-closed even when empty.
 *  `<style/>` and `<text/>` self-closed are legal XML but have tripped up
 *  enough SVG consumers over the years that emitting the long form is simply
 *  cheaper than finding out which ones. */
const NEVER_SELF_CLOSE = new Set(["style", "text", "tspan", "g", "defs", "clipPath", "filter"]);

export function serializeIR(ir: SvgIR): string {
  const attrs = Object.entries(ir.attrs)
    .map(([key, value]) => ` ${key}="${escapeAttr(String(value))}"`)
    .join("");

  const hasChildren = ir.children !== undefined && ir.children.length > 0;
  const hasText = ir.text !== undefined && ir.text.length > 0;

  if (!hasChildren && !hasText && !NEVER_SELF_CLOSE.has(ir.tag)) {
    return `<${ir.tag}${attrs}/>`;
  }

  const body = hasChildren
    ? ir.children!.map(serializeIR).join("")
    : hasText
      ? escapeText(ir.tag, ir.text!)
      : "";

  return `<${ir.tag}${attrs}>${body}</${ir.tag}>`;
}

const escapeAttr = (value: string): string =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");

/**
 * Text content escaping.
 *
 * `<style>` is deliberately exempt: it carries CSS containing `@font-face`
 * rules with base64 `data:` URIs, and escaping those would corrupt them. CSS
 * is not parsed as XML character data by any SVG renderer we target, and the
 * content is generated by our own resolver rather than user input — but note
 * that if a user-supplied font *family name* ever reaches a style rule, it
 * needs sanitising at that boundary, not here.
 */
function escapeText(tag: string, text: string): string {
  if (tag === "style") return text;
  return text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

/** Full document string, with the XML prolog resvg prefers. */
export function serializeDocument(ir: SvgIR): string {
  return `<?xml version="1.0" encoding="UTF-8"?>${serializeIR(ir)}`;
}
