import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Better Auth CLI — never linted or hand-edited.
    "src/lib/db/schema/auth.ts",
  ]),

  // Tenancy guard: the raw `db` client must only be reached through the
  // organization-scoped repository in src/lib/db/scope.ts. Forbidding the
  // import everywhere else makes an accidental unscoped, cross-tenant query a
  // lint error rather than a code-review hope. Discipline decays; a rule does
  // not. This is the mechanical half of the isolation model documented in
  // scope.ts.
  {
    files: ["src/**/*.{ts,tsx}"],
    // src/lib/db/** IS the repository. src/lib/auth/server.ts is the one other
    // legitimate consumer: Better Auth's adapter operates directly on the
    // user/session/organization tables, which have no organization filter to
    // apply — scoping them would be meaningless. No other exemptions.
    ignores: ["src/lib/db/**", "src/lib/auth/server.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/lib/db/client", "**/db/client"],
              message:
                "Do not import the raw db client. Go through scoped(orgScope) in @/lib/db/scope so every query is organization-filtered.",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
