// ============================================
// QUICKARDS — New project client form
// ============================================
//
// Kept client-side only for the form submission; available templates arrive
// from the server route so the browser never asks for an unscoped list.

"use client";

import { ArrowRight, FileSpreadsheet, FolderUp, LayoutTemplate } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";

import Button from "@/components/ui/Button";

export default function NewProjectForm({ templates }: { templates: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [name, setName] = useState("Untitled batch"); const [templateId, setTemplateId] = useState(templates[0]?.id ?? ""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch("/api/projects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, templateId: templateId || undefined }) }); const data = await response.json().catch(() => null) as { id?: string; error?: string } | null; if (!response.ok || !data?.id) { setError(data?.error ?? "Could not create the project"); setSaving(false); return; } router.replace(`/projects/${data.id}`); }
  return <div className="mx-auto max-w-3xl py-8 sm:py-14"><div className="grid gap-8 lg:grid-cols-[1fr_.72fr]"><div><p className="qk-kicker">New batch</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Create a project</h1><p className="mt-3 max-w-lg text-sm leading-6 text-[var(--k-text-muted)]">Give this batch a name and select the card design it will render from. You will add data and photos in the next step.</p><div className="mt-8 hidden space-y-4 lg:block"><WorkflowStep icon={<LayoutTemplate className="size-4" />} label="Choose a saved template" /><WorkflowStep icon={<FileSpreadsheet className="size-4" />} label="Upload your roster as a CSV" /><WorkflowStep icon={<FolderUp className="size-4" />} label="Match photos and render output" /></div></div><form className="space-y-5 rounded-[calc(var(--k-radius)+7px)] border border-[var(--k-border)] bg-[var(--k-surface)] p-6 shadow-[var(--k-shadow)] sm:p-7" onSubmit={create}><div><label htmlFor="project-name" className="text-sm font-semibold">Project name</label><p className="mt-1 text-xs text-[var(--k-text-muted)]">Use a name your team will recognize later.</p><input id="project-name" className="mt-3 h-11 w-full rounded-[var(--k-radius)] border border-[var(--k-border)] bg-[var(--k-bg)] px-3 text-sm outline-none transition focus:border-[var(--k-accent-border)] focus:ring-2 focus:ring-[var(--k-accent-soft)]" value={name} onChange={(event) => setName(event.target.value)} required autoFocus /></div><div><label htmlFor="template" className="text-sm font-semibold">Template</label><p className="mt-1 text-xs text-[var(--k-text-muted)]">The selected design is pinned to this batch.</p><select id="template" className="mt-3 h-11 w-full rounded-[var(--k-radius)] border border-[var(--k-border)] bg-[var(--k-bg)] px-3 text-sm outline-none transition focus:border-[var(--k-accent-border)] focus:ring-2 focus:ring-[var(--k-accent-soft)]" value={templateId} onChange={(event) => setTemplateId(event.target.value)} required><option value="" disabled>Select a template</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></div>{templates.length === 0 && <p className="rounded-[var(--k-radius)] bg-[color-mix(in_srgb,var(--k-danger)_10%,transparent)] p-3 text-sm text-[var(--k-danger)]">Create a template first, then return to start a project.</p>}{error && <p className="rounded-[var(--k-radius)] bg-[color-mix(in_srgb,var(--k-danger)_10%,transparent)] p-3 text-sm text-[var(--k-danger)]">{error}</p>}<div className="flex items-center justify-end gap-3 border-t border-[var(--k-border)] pt-5"><Button href="/projects" variant="ghost">Cancel</Button><Button type="submit" loading={saving} disabled={!templateId} icon={<ArrowRight className="size-4" />}>Continue</Button></div></form></div></div>;
}

function WorkflowStep({ icon, label }: { icon: React.ReactNode; label: string }) { return <div className="flex items-center gap-3 text-sm text-[var(--k-text-muted)]"><span className="grid size-8 place-items-center rounded-[var(--k-radius)] bg-[var(--k-accent-soft)] text-[var(--k-accent)]">{icon}</span>{label}</div>; }
